### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by dev01d** [swift-linux/swift-linux#2]
Looks like serving the repo through the GitHub wildcard SSL causes this error in the browser NET::ERR_CERT_COMMON_NAME_INVALID  and this one while adding the remote.
```bash
$ flatpak --user remote-add swift https://swift-flatpak.refi64.com/swift.flatpakrepo
Can't load uri https://swift-flatpak.refi64.com/swift.flatpakrepo: Unacceptable TLS certificate
```

**Comment by refi64** [comment]
Honestly, the Swift builds here are quite old and I won't have time to
update them for the foreseeable future. The whole idea of binary matching
the dynamic linker was pretty fun, but in practice it was also a headache
to maintain...

The only *actual* long-term solution here would be to do a full source
build for Swift. I had some work on this as well, but the builds take quite
a bit of time, and I kept running into nasty linking issues that I again
didn't really have to time to look into further.

**Comment by dev01d** [comment]
Yeah it seems like packaging swift for Linux has a lot of random blocking issues right now. This issue was just sort of a sanity check incase anyone after me ran into the same error.
